version: '3'
services:
  convertor:
    build: .
    volumes:
      - ./:/opt/
    command: "make run"
    stdin_open: true
    tty: true

  test:
    build:
      context: ./
      dockerfile: Dockerfile.test
    volumes:
      - ./:/opt/
    command: "make test"
    stdin_open: true
    tty: true

  lint:
    build:
      context: ./
      dockerfile: Dockerfile.test
    volumes:
      - ./:/opt/
    command: "make lint"
    stdin_open: true
    tty: true
